// Generated from the 2026-07-29 machine-research package. Do not edit by hand.
export const machineResearchImageSubmissions = [
  {
    "masterFamilyId": "M-034",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "DB2-B755",
    "plateModelVisible": "Manual covers identify DB2-B755; centre photograph plate is not fully legible at supplied resolution",
    "suppliedFilename": "M-034_brother_db2_b755_user_reference_composite.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-034_brother_db2_b755_user_reference_composite.png",
    "libraryDecision": "Supplementary only — current exact-model photograph remains the main reference",
    "visualAssessment": "Exact-model supporting reference sheet",
    "evidenceNote": "Useful corroborating composite containing two DB2-B755 manual covers and a machine photograph. It is not promoted because the existing main reference is a cleaner single-machine image.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-025",
    "manufacturer": "Union Special",
    "modelSuppliedByUser": "35800DN",
    "plateModelVisible": "No DN suffix or style plate visible",
    "suppliedFilename": "M-025_union_special_35800dn_user_candidate_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-025_union_special_35800dn_user_candidate_photo.png",
    "libraryDecision": "Supplementary only — retain family-level certainty",
    "visualAssessment": "Union Special 35800-family photograph; DN suffix not visually confirmed",
    "evidenceNote": "The image is consistent with the 35800 family, but the DN suffix cannot be read. Preserve as a candidate reference and keep « À confirmer » for the subclass.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-014",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "MA4-V92-92-6",
    "plateModelVisible": "Yes — MA4-V92-92-6",
    "suppliedFilename": "M-014_brother_ma4_v92_92_6_user_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-014_brother_ma4_v92_92_6_user_photo.png",
    "libraryDecision": "Promoted to main reference",
    "visualAssessment": "Exact-model photograph with visible subclass plate",
    "evidenceNote": "Clear whole-head photograph with the MA4-V92-92-6 plate visible. This is stronger identity evidence than the previous adjacent-subclass dealer photograph.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-027",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "LT2-B832-5",
    "plateModelVisible": "Yes — LT2-B832-5",
    "suppliedFilename": "M-027_brother_lt2_b832_5_user_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-027_brother_lt2_b832_5_user_photo.png",
    "libraryDecision": "Promoted to main reference",
    "visualAssessment": "Exact-model photograph with visible subclass plate",
    "evidenceNote": "Clear whole-head photograph with the LT2-B832-5 plate visible. A watermark remains, so it is for internal identification until the original source and reuse terms are recorded.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-032",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "LT2-B833",
    "plateModelVisible": "No readable model plate in the supplied screenshot",
    "suppliedFilename": "M-032_brother_lt2_b833_user_manual_photo_candidate.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-032_brother_lt2_b833_user_manual_photo_candidate.png",
    "libraryDecision": "Promoted as a cautious family reference",
    "visualAssessment": "Whole-machine manual photograph candidate; B833 label not visible",
    "evidenceNote": "The screenshot shows a complete Brother feed mechanism consistent with the supplied LT2-B833 identification, but the plate and source page are absent. Use as an indicative family visual and keep « À confirmer ».",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-033",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "DB2-B737",
    "plateModelVisible": "A DB2-B737-series plate appears present but is not legible enough to confirm the subclass",
    "suppliedFilename": "M-033_brother_db2_b737_user_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-033_brother_db2_b737_user_photo.png",
    "libraryDecision": "Supplementary only — retain the licensed Wikimedia main reference",
    "visualAssessment": "DB2-B737-series supporting photograph",
    "evidenceNote": "Useful installed-machine view, but the existing Wikimedia photograph remains clearer and has documented CC BY-SA 4.0 reuse terms.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-034",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "DB2-B755",
    "plateModelVisible": "A DB2-B755-series plate is visible; subclass text remains small",
    "suppliedFilename": "M-034_brother_db2_b755_user_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-034_brother_db2_b755_user_photo.png",
    "libraryDecision": "Supplementary only — current clean exact-model photograph remains the main reference",
    "visualAssessment": "Exact-model supporting photograph",
    "evidenceNote": "Clearer than the earlier composite, but it is watermarked and does not improve on the clean main reference enough to replace it.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-035",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "DB2-B724",
    "plateModelVisible": "No readable model plate; image is low resolution",
    "suppliedFilename": "M-035_brother_db2_b724_user_candidate_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-035_brother_db2_b724_user_candidate_photo.png",
    "libraryDecision": "Promoted as a cautious family reference",
    "visualAssessment": "Whole-machine candidate photograph; DB2-B724 plate not visible",
    "evidenceNote": "This supplies the first usable whole-machine visual for the DB2-B724 record, but the low resolution and absent plate mean it must remain « Photo indicative — modèle à confirmer ».",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-039",
    "manufacturer": "Juki",
    "modelSuppliedByUser": "MO-3900 series; photographed subclass MO-3916",
    "plateModelVisible": "Yes — MO-3916",
    "suppliedFilename": "M-039_juki_mo_3900_series_mo_3916_user_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-039_juki_mo_3900_series_mo_3916_user_photo.png",
    "libraryDecision": "Promoted to main family reference",
    "visualAssessment": "Plate-visible MO-3916 photograph representing the MO-3900 series",
    "evidenceNote": "The plate reads MO-3916. It is good evidence for the MO-3900 family but must not be captioned as an unsuffixed MO-3900 model.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-040",
    "manufacturer": "Juki",
    "modelSuppliedByUser": "MO-3914",
    "plateModelVisible": "Yes — MO-3914",
    "suppliedFilename": "M-040_juki_mo_3914_user_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-040_juki_mo_3914_user_photo.png",
    "libraryDecision": "Promoted to main reference",
    "visualAssessment": "Exact-model photograph with visible plate",
    "evidenceNote": "Clear complete-head photograph with MO-3914 visible on the plate. A watermark remains, so public reuse still needs provenance.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-041",
    "manufacturer": "Union Special",
    "modelSuppliedByUser": "35800",
    "plateModelVisible": "No readable style suffix",
    "suppliedFilename": "M-025_union_special_35800dn_user_candidate_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-025_union_special_35800dn_user_candidate_photo.png",
    "libraryDecision": "Duplicate of the earlier 35800DN candidate — preserved once; current main reference retained",
    "visualAssessment": "Union Special 35800-family photograph",
    "evidenceNote": "The submitted pixels are identical to the earlier M-025 candidate file. The clean existing M-041 main reference remains stronger.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-042",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "BAS-304A",
    "plateModelVisible": "Model plate is not readable at this angle",
    "suppliedFilename": "M-042_brother_bas_304a_user_duplicate_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-042_brother_bas_304a_user_duplicate_photo.png",
    "libraryDecision": "Supplementary duplicate view — current exact-model main reference retained",
    "visualAssessment": "BAS-304A supporting photograph",
    "evidenceNote": "This is visually the same product image already used for M-042, supplied here in PNG form. It is retained in the submission register but does not change certainty.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-044",
    "manufacturer": "Willcox & Gibbs",
    "modelSuppliedByUser": "515-4 series",
    "plateModelVisible": "Brand plate visible; exact 515-4 subclass is not legible",
    "suppliedFilename": "M-044_willcox_gibbs_515_4_user_candidate_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-044_willcox_gibbs_515_4_user_candidate_photo.png",
    "libraryDecision": "Promoted to main family reference",
    "visualAssessment": "Willcox & Gibbs machine photograph supplied as 515-4; subclass not visually confirmed",
    "evidenceNote": "This is closer to the supplied 515-4 identification than the previous 515-E32 reference, but the model suffix is not readable. Keep the 515-4 classification « À confirmer ».",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-046",
    "manufacturer": "Singer",
    "modelSuppliedByUser": "302W401",
    "plateModelVisible": "Singer branding visible; 302W401 model plate not visible",
    "suppliedFilename": "M-046_singer_302w401_user_candidate_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-046_singer_302w401_user_candidate_photo.png",
    "libraryDecision": "Promoted to main family reference",
    "visualAssessment": "Singer multi-needle machine supplied as 302W401; subclass not visually confirmed",
    "evidenceNote": "The image is a closer candidate for the 302W401 record than the previous known 302W206 family reference, but no 302W401 plate is visible. Keep the subclass « À confirmer ».",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-047",
    "manufacturer": "Juki",
    "modelSuppliedByUser": "LH-1152",
    "plateModelVisible": "Yes — LH-1152; the -4 / -5 subclass suffix is not shown",
    "suppliedFilename": "M-047_juki_lh_1152_user_plate_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-047_juki_lh_1152_user_plate_photo.png",
    "libraryDecision": "Promoted to main reference",
    "visualAssessment": "Exact LH-1152 model-family photograph with visible plate; subclass suffix still requires verification",
    "evidenceNote": "The head plate clearly reads LH-1152, making this stronger identity evidence than the previous dealer photograph. The legacy -4 / -5 subclass remains « À confirmer » until the full plate or machine record is checked.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-048",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "BAS-341",
    "plateModelVisible": "No readable model plate; full installation is visible",
    "suppliedFilename": "M-048_brother_bas_341_user_system_candidate.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-048_brother_bas_341_user_system_candidate.png",
    "libraryDecision": "Supplementary only — current sourced BAS-341A-family manual illustration remains the main reference",
    "visualAssessment": "Whole-installation BAS-341 candidate; exact unsuffixed subclass is not visually confirmed",
    "evidenceNote": "The image is useful for recognizing the complete automated sewing station, but no readable plate or source page was supplied. Keep the sourced manual illustration as the main reference and retain « À confirmer » for BAS-341 versus BAS-341A.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-054",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "MA4-B851",
    "plateModelVisible": "No readable model plate; Brother branding and overlock configuration are visible",
    "suppliedFilename": "M-054_brother_ma4_b851_user_manual_candidate.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-054_brother_ma4_b851_user_manual_candidate.png",
    "libraryDecision": "Promoted as a cautious family reference",
    "visualAssessment": "Brother overlock whole-machine reference supplied as MA4-B851; exact model plate is not visible",
    "evidenceNote": "This fills the former visual gap with a recognizable Brother overlock head, but the screenshot does not expose an MA4-B851 plate. Caption « Photo indicative — modèle à confirmer » and request a physical nameplate photograph.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-055",
    "manufacturer": "Union Special",
    "modelSuppliedByUser": "63900DM",
    "plateModelVisible": "Union Special branding and a 63900-style badge are visible; the DM suffix is not readable",
    "suppliedFilename": "M-055_union_special_63900dm_user_manual_candidate.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-055_union_special_63900dm_user_manual_candidate.png",
    "libraryDecision": "Supplementary only — current sourced 63900-family photograph remains the main reference",
    "visualAssessment": "Union Special 63900-family manual photograph; DM suffix not visually confirmed",
    "evidenceNote": "The image is consistent with the 63900 family but does not prove the DM subclass. The existing sourced family photograph remains the main reference; this screenshot is preserved as supporting evidence.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-023",
    "manufacturer": "Eastman",
    "modelSuppliedByUser": "Blue Streak II 629",
    "plateModelVisible": "Blue Streak II product label is visible; the small class/model fields are not readable at this resolution",
    "suppliedFilename": "M-023_eastman_blue_streak_ii_629_user_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-023_eastman_blue_streak_ii_629_user_photo.png",
    "libraryDecision": "Supplementary only — current sourced exact-model product photograph remains the main reference",
    "visualAssessment": "High-quality Blue Streak II product photograph; 629 class field not legible",
    "evidenceNote": "This is an excellent recognition image, but the current Eastman distributor reference already has exact-model provenance. Preserve this version as supporting evidence until its original webpage and reuse rights are known.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-022",
    "manufacturer": "Mitsubishi",
    "modelSuppliedByUser": "DN-267",
    "plateModelVisible": "Manual header lists DN-260 / DN-262 / DN-265 / DN-267; illustrated body badge reads DN-260",
    "suppliedFilename": "M-022_mitsubishi_dn_260_262_265_267_manual_drawing.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-022_mitsubishi_dn_260_262_265_267_manual_drawing.png",
    "libraryDecision": "Promoted as a whole-machine manual illustration",
    "visualAssessment": "Shared DN-260 / DN-262 / DN-265 / DN-267 family drawing; not an exact DN-267 depiction",
    "evidenceNote": "The manual header explicitly includes DN-267, but the drawn nameplate says DN-260. Use only as « Schéma de référence — famille DN-260/262/265/267 » and obtain a physical DN-267 plate and full-machine photograph.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-028",
    "manufacturer": "Kansai Special",
    "modelSuppliedByUser": "W-842",
    "plateModelVisible": "Kansai Special branding is visible; the small model plate is not readable",
    "suppliedFilename": "M-028_kansai_special_w_842_user_catalogue_candidate.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-028_kansai_special_w_842_user_catalogue_candidate.png",
    "libraryDecision": "Promoted as a cautious family reference",
    "visualAssessment": "Kansai Special W-series catalogue photograph supplied as W-842; exact plate not readable",
    "evidenceNote": "The image is consistent with the W-series and was supplied as W-842, but the model plate cannot be read. Keep « Photo indicative — modèle à confirmer » until the catalogue caption or a physical W-842 plate is obtained.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-029",
    "manufacturer": "Kansai Special",
    "modelSuppliedByUser": "W-8042",
    "plateModelVisible": "No readable model plate; the file was specifically supplied and named as W-8042",
    "suppliedFilename": "M-029_kansai_special_w_8042_user_candidate_photo.jpg",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-029_kansai_special_w_8042_user_candidate_photo.jpg",
    "libraryDecision": "Promoted as a cautious family reference",
    "visualAssessment": "Kansai Special W-series whole-machine photograph supplied as W-8042; exact plate not visible",
    "evidenceNote": "This is a clear whole-machine view specifically supplied as W-8042, but the photograph does not show a readable model plate or source page. Use « Photo indicative — modèle à confirmer » pending a plate or authoritative catalogue caption.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-012",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "BAS-301",
    "plateModelVisible": "No readable branding or model plate at the supplied resolution; the complete automated station is visible",
    "suppliedFilename": "M-012_brother_bas_301_user_low_resolution_candidate.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-012_brother_bas_301_user_low_resolution_candidate.png",
    "libraryDecision": "Supplementary only — current sourced BAS-301 manual illustration remains the main reference",
    "visualAssessment": "Low-resolution complete-station view supplied as BAS-301; exact model is not visually verifiable",
    "evidenceNote": "The photograph helps recognize the cabinet-style automated station but is too small to verify BAS-301 markings or controls. Preserve it as supporting evidence; keep the sharper sourced BAS-301 manual illustration as the main reference.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-015",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "BAS-341A",
    "plateModelVisible": "Brother branding and the complete programmable station are visible; no readable BAS-341A model plate",
    "suppliedFilename": "M-015_brother_bas_341a_user_station_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-015_brother_bas_341a_user_station_photo.png",
    "libraryDecision": "Promoted as a cautious family reference",
    "visualAssessment": "Clear Brother programmable sewing-station photograph supplied as BAS-341A; exact subclass plate is not visible",
    "evidenceNote": "This installed-machine photograph is more useful for recognition than the previous manual drawing and shows the complete Brother head, work clamp, table and control unit. No BAS-341A plate is readable, so caption « Photo indicative — modèle à confirmer » until the source page or physical plate confirms the subclass.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-007",
    "manufacturer": "Union Special",
    "modelSuppliedByUser": "56900J",
    "plateModelVisible": "Union Special branding is visible; the small style plate is not readable enough to confirm the J suffix",
    "suppliedFilename": "M-007_union_special_56900j_user_candidate_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-007_union_special_56900j_user_candidate_photo.png",
    "libraryDecision": "Promoted as a cautious family reference",
    "visualAssessment": "Clean Union Special flat-bed machine photograph supplied as 56900J; exact style suffix is not readable",
    "evidenceNote": "This fills the last sewing-machine visual gap with a useful whole-head photograph. The image is consistent with the Union Special 56900 family, but the J suffix cannot be read; caption « Photo indicative — modèle à confirmer » pending a plate or source page.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-022",
    "manufacturer": "Mitsubishi",
    "modelSuppliedByUser": "DN-267",
    "plateModelVisible": "Manual header lists DN-260 / DN-262 / DN-265 / DN-267; illustrated body badge reads DN-260",
    "suppliedFilename": "M-022_mitsubishi_dn_260_262_265_267_user_repeat_drawing.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-022_mitsubishi_dn_260_262_265_267_user_repeat_drawing.png",
    "libraryDecision": "Supplementary repeat — current wider version of the same shared-series drawing remains the main reference",
    "visualAssessment": "Second capture of the DN-260 / DN-262 / DN-265 / DN-267 family drawing; not an exact DN-267 depiction",
    "evidenceNote": "The newly supplied capture repeats the same family drawing already selected. Because the drawn nameplate says DN-260, it does not upgrade the DN-267 identification and is retained only as submission evidence.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-019",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "BAS-311A",
    "plateModelVisible": "Brother branding and the complete programmable station are visible; no readable BAS-311A plate",
    "suppliedFilename": "M-019_brother_bas_311a_user_station_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-019_brother_bas_311a_user_station_photo.png",
    "libraryDecision": "Promoted as a cautious family reference",
    "visualAssessment": "Clear whole-station Brother programmable sewing-machine photograph supplied as BAS-311A; exact plate not visible",
    "evidenceNote": "This real whole-station photograph is more useful for recognition than the previous manual drawing. No BAS-311A plate or source page is visible, so keep « Photo indicative — modèle à confirmer ».",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-048",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "BAS-341",
    "plateModelVisible": "Model-specific BAS-341 parts-book context supplied; the machine plate is not readable in the screenshot",
    "suppliedFilename": "M-048_brother_bas_341_user_parts_book_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-048_brother_bas_341_user_parts_book_photo.png",
    "libraryDecision": "Promoted as a model-specific whole-machine manual reference",
    "visualAssessment": "Whole-machine photograph from the BAS-341 model-specific parts book",
    "evidenceNote": "The supplied parts book is explicitly titled BAS-341 and contains this whole-machine view. Use as « Schéma/photo de manuel — BAS-341 »; public reuse still requires rights review or replacement with a factory-owned photograph.",
    "originalSourceUrl": "https://www.szwalnicze.com/cat_brother/brother_BAS-341.pdf",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-054",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "MA4-B851",
    "plateModelVisible": "Brother branding and overlock configuration are visible; no readable MA4-B851 plate",
    "suppliedFilename": "M-054_brother_ma4_b851_user_catalogue_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-054_brother_ma4_b851_user_catalogue_photo.png",
    "libraryDecision": "Promoted as a clearer cautious family reference",
    "visualAssessment": "Clear isolated Brother overlock photograph supplied as MA4-B851; exact model plate not visible",
    "evidenceNote": "This is a clearer recognition image than the previous parts-reference screenshot, but it still does not expose an MA4-B851 plate or source caption. Keep « Photo indicative — modèle à confirmer ».",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-055",
    "manufacturer": "Union Special",
    "modelSuppliedByUser": "63900DM",
    "plateModelVisible": "Union Special branding is visible; the 63900DM style suffix is not readable",
    "suppliedFilename": "M-055_union_special_63900dm_user_catalogue_candidate.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-055_union_special_63900dm_user_catalogue_candidate.png",
    "libraryDecision": "Supplementary only — current sourced 63900-family photograph remains the main reference",
    "visualAssessment": "Union Special whole-head photograph supplied as 63900DM; exact DM suffix not visible",
    "evidenceNote": "The image is useful family evidence but does not prove the DM suffix. The existing sourced 63900-family photograph remains the main reference.",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-046",
    "manufacturer": "Singer",
    "modelSuppliedByUser": "302W401",
    "plateModelVisible": "No readable Singer branding or 302W401 plate; multi-needle configuration is visible",
    "suppliedFilename": "M-046_singer_302w401_user_high_resolution_candidate.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-046_singer_302w401_user_high_resolution_candidate.png",
    "libraryDecision": "Promoted as a clearer cautious family reference",
    "visualAssessment": "High-resolution multi-needle machine photograph supplied as Singer 302W401; exact identity is not visible",
    "evidenceNote": "The photograph clearly shows the multi-needle waistband-style configuration and is a stronger recognition image than the previous candidate. No Singer or 302W401 plate is visible, so the exact model remains « À confirmer ».",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-032",
    "manufacturer": "Brother",
    "modelSuppliedByUser": "LT2-B833",
    "plateModelVisible": "Model-specific LT2-B833 parts-book context supplied; subclass -603 remains unreadable",
    "suppliedFilename": "M-032_brother_lt2_b833_user_parts_book_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-032_brother_lt2_b833_user_parts_book_photo.png",
    "libraryDecision": "Promoted to main model reference",
    "visualAssessment": "Whole-machine photograph from the LT2-B833 model-specific parts book; -603 subclass not confirmed",
    "evidenceNote": "The model-specific parts book establishes the LT2-B833 identity for this whole-machine photograph. The legacy -603 / -603V configuration remains « À confirmer » until the physical plate is checked.",
    "originalSourceUrl": "https://www.szwalnicze.com/cat_brother/brother_LT2-B833.pdf",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-028",
    "manufacturer": "Kansai Special",
    "modelSuppliedByUser": "W-842 comparison; photographed model WX-8842",
    "plateModelVisible": "Yes — WX-8842-series plate; this is not a W-842 plate",
    "suppliedFilename": "M-028_kansai_wx_8842_adjacent_candidate.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-028_kansai_wx_8842_adjacent_candidate.png",
    "libraryDecision": "Supplementary only — adjacent WX-8842 comparison must not replace the W-842 main reference",
    "visualAssessment": "Clear Kansai WX-8842 adjacent-model photograph; visually similar but not evidence of W-842",
    "evidenceNote": "The visible plate identifies a WX-8842-series machine, not W-842. Preserve it as an adjacent-family comparison only and keep the W-842 record « À confirmer ».",
    "originalSourceUrl": "",
    "rightsAttribution": "Original webpage and rights not supplied; internal identification only until provenance is added.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-052",
    "manufacturer": "Galkin / Union Special",
    "modelSuppliedByUser": "Galkin belt-loop attachment/conversion on Union Special 57700; legacy 11000KL designation unverified",
    "plateModelVisible": "Yes — GALKIN attachment branding and Union Special style plate 57700 are visible; the style suffix and 11000KL are not visible",
    "suppliedFilename": "M-052_galkin_attachment_union_special_57700_atlas_levy_reference.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-052_galkin_attachment_union_special_57700_atlas_levy_reference.png",
    "libraryDecision": "Promoted as a cautious attachment-family reference",
    "visualAssessment": "Galkin-branded belt-loop conversion on a plate-visible Union Special 57700; exact factory configuration and 11000KL code remain unconfirmed",
    "evidenceNote": "The visible GALKIN unit, long drive shaft and front cutter/guide hardware are consistent with the inventory’s knives, linkage, belt tractor/coupling, pulleys and folder terminology. This supports a belt-loop attachment/conversion role, but it does not establish 11000KL as a published Galkin model or identify the factory’s exact host configuration.",
    "originalSourceUrl": "https://atlaslevy.com/Union-Special-57700-Coverstitch-Used-Head-Only_p_3568.html",
    "rightsAttribution": "Reference copy from an Atlas Levy used-machine listing. Public reuse requires permission from the source owner or replacement with a factory-owned photograph.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-049",
    "manufacturer": "Willcox & Gibbs",
    "modelSuppliedByUser": "E32 series; normalizes legacy label WILLCOX E 32 to WILLCOX E32",
    "plateModelVisible": "No machine plate; the 1983 parts-catalogue cover explicitly lists models E32, E52 and E56",
    "suppliedFilename": "M-049_willcox_gibbs_e32_e52_e56_1983_parts_catalogue_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-049_willcox_gibbs_e32_e52_e56_1983_parts_catalogue_photo.png",
    "libraryDecision": "Promoted as an authoritative E-series manual reference",
    "visualAssessment": "Whole-machine photograph from the Willcox & Gibbs E32/E52/E56 parts-catalogue cover; exact E32 class, gauge and application suffix are not isolated by the image",
    "evidenceNote": "The catalogue establishes E32 as a documented Willcox & Gibbs model series and supports normalizing spacing variants such as WILLCOX E 32 and WILLCOX E-32 to WILLCOX E32. The cover photograph represents the shared E32/E52/E56 series and does not establish the factory machine’s full style number, class prefix, gauge or application suffix.",
    "originalSourceUrl": "https://www.scribd.com/document/371262735/Pegasus-E-Series",
    "rightsAttribution": "Reference crop from a historic Willcox & Gibbs parts catalogue hosted on Scribd/Superior Sewing. Public reuse requires rights review or replacement with a factory-owned photograph.",
    "dateReceived": "2026-07-29"
  },
  {
    "masterFamilyId": "M-045",
    "manufacturer": "Willcox & Gibbs / Pegasus",
    "modelSuppliedByUser": "515-E32-430; probable interpretation of legacy WILLCOX GIBBS 515/532",
    "plateModelVisible": "Yes — factory type plate reads 515-E32-430",
    "suppliedFilename": "M-045_willcox_gibbs_515_e32_430_plate_visible_user_photo.png",
    "localRelativePath": "machine_reference_images_photo_first/user_supplied/M-045_willcox_gibbs_515_e32_430_plate_visible_user_photo.png",
    "libraryDecision": "Promoted to main reference",
    "visualAssessment": "Exact-model photograph with clearly visible Willcox & Gibbs type plate 515-E32-430 and Pegasus branding",
    "evidenceNote": "The plate reads 515-E32-430, not 515-E532. This strongly supports reading the legacy 515/532 string as a damaged transcription of 515-E32. Keep the original inventory wording unchanged and do not apply the -430 style suffix to every 515-series record without its own asset-level plate.",
    "originalSourceUrl": "",
    "rightsAttribution": "User-supplied reference photograph; original webpage, creator and reuse rights not supplied. Internal identification only until provenance and permission are documented.",
    "dateReceived": "2026-07-29"
  }
] as const;
