export type SupplierContactSeed = {
  supplierCode: string;
  supplierName: string;
  address: string;
  phone: string;
  email: string;
  website: string;
  statusKey: "active" | "inactive" | "verify" | "not_supplier";
  statusDetail: string;
  statusNote: string;
  sourceUrl: string;
  verifiedDate: string;
};

// Contact research supplied by Confection NF Denim on 2026-07-29.
// Email addresses were not present in the source and remain editable in the app.
export const supplierContactSeed: SupplierContactSeed[] = [
  {
    "supplierCode": "125",
    "supplierName": "AMC REECE (A.M.F.)",
    "address": "Tovární 837/9C, 798 11 Prostějov, Czech Republic",
    "phone": "+420 725 088 560",
    "email": "",
    "website": "https://www.amfreece-cars.cz",
    "statusKey": "active",
    "statusDetail": "Active (official website)",
    "statusNote": "Confirmed as AMF Reece–Cars s.r.o. (also called AMC Reece/A.M.F.); its official contact page identifies it as a current industrial sewing-machine manufacturer.",
    "sourceUrl": "https://www.amfreece-cars.cz/contacts/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "335",
    "supplierName": "AGENCE PIERRE GRENIER INC.",
    "address": "10775 Avenue Racette, Montréal-Nord, QC H1G 5H5, Canada",
    "phone": "514-327-7650",
    "email": "",
    "website": "https://pierregrenier.com",
    "statusKey": "active",
    "statusDetail": "Active (corporation verified)",
    "statusNote": "Federal record is active; public operating contact differs from the registered office.",
    "sourceUrl": "https://ised-isde.canada.ca/cc/lgcy/fdrlCrpDtls.html?corpId=3987906",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "90",
    "supplierName": "BRUCK SEWING MACHINE CO.",
    "address": "6749A boul. Saint-Laurent, Montréal, QC H2S 3C8, Canada",
    "phone": "514-273-2888",
    "email": "",
    "website": "",
    "statusKey": "verify",
    "statusDetail": "Unverified — legacy directory listing",
    "statusNote": "No current official web presence found; confirm before ordering.",
    "sourceUrl": "https://m.seo-ags.com/contact-supplier?id=25602261017",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "13",
    "supplierName": "C.R.V. LTEE.",
    "address": "2186 boul. de la Métropole, Longueuil, QC J4G 1R5, Canada",
    "phone": "514-388-9273",
    "email": "",
    "website": "https://www.civit.ca",
    "statusKey": "active",
    "statusDetail": "Active (successor / associated distributor)",
    "statusNote": "C.R.V. is linked to Civit Machines à Coudre: Civit states that its Montréal operation was founded by Marcel Rivard, former president and founder of CRV Équipements d'aiguilles. Civit is listed by JUKI as its Canadian distributor.",
    "sourceUrl": "https://www.civit.ca/fr/entreprise.htm",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "8",
    "supplierName": "CANADIAN PAPER",
    "address": "3001 rue Brabant-Marineau, Saint-Laurent, QC H4S 1V5, Canada",
    "phone": "514-333-4040",
    "email": "",
    "website": "https://www.imperialdade.com",
    "statusKey": "active",
    "statusDetail": "Active (corporation / operating division)",
    "statusNote": "Canadian Paper & Packaging is listed as an active corporation; contact is associated with CPP / Imperial Dade Canada.",
    "sourceUrl": "https://ised-isde.canada.ca/cc/lgcy/fdrlCrpDtls.html?corpId=16048862",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "10",
    "supplierName": "CENTRAL SEWING MACHINE INC.",
    "address": "18514 104 Avenue NW, Edmonton, AB T5S 0K3, Canada",
    "phone": "780-486-0047",
    "email": "",
    "website": "https://www.centralsewing.com",
    "statusKey": "active",
    "statusDetail": "Active (recent business listing)",
    "statusNote": "Current opening hours and contact details were updated in 2025.",
    "sourceUrl": "https://www.cylex-canada.ca/company/central-sewing-machine-inc--24701959.html",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "356",
    "supplierName": "COMPRESSEURS DUBREUIL",
    "address": "3030 rue King Ouest, Sherbrooke, QC J1L 1Y7, Canada",
    "phone": "819-822-0513",
    "email": "",
    "website": "",
    "statusKey": "active",
    "statusDetail": "Active (directory / enterprise listing)",
    "statusNote": "Public enterprise listing reports an active business; confirm its current product line before ordering.",
    "sourceUrl": "https://www.allbiz.ca/fr/compresseurs-dubreuil-inc-819-822-0513",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "113",
    "supplierName": "COWPER",
    "address": "677, 7e Avenue, Lachine, QC H8S 3A1, Canada",
    "phone": "1-888-506-1111",
    "email": "",
    "website": "https://cowper.ca",
    "statusKey": "active",
    "statusDetail": "Active (official website)",
    "statusNote": "Cowper Automation lists current support and office details.",
    "sourceUrl": "https://cowper.ca/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "323",
    "supplierName": "DISCA INC",
    "address": "10837 avenue Moisan, Montréal-Nord, QC H1G 4N6, Canada",
    "phone": "514-360-6604",
    "email": "",
    "website": "https://www.disca.ca",
    "statusKey": "active",
    "statusDetail": "Active (possible name match)",
    "statusNote": "Matched to Les Constructions Disca inc.; confirm it is the inventory vendor.",
    "sourceUrl": "https://membres.apesiq.org/fr/repertoire/constructions-disca-inc-les",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "1000",
    "supplierName": "DIVERS",
    "address": "",
    "phone": "",
    "email": "",
    "website": "",
    "statusKey": "not_supplier",
    "statusDetail": "Not a supplier record",
    "statusNote": "Generic catch-all label in the inventory; no company to verify.",
    "sourceUrl": "",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "262",
    "supplierName": "ELECTRO-BEAUCE INC.",
    "address": "2250, 90e Rue, Saint-Georges, QC G5Y 7J7, Canada",
    "phone": "418-228-5505",
    "email": "",
    "website": "https://www.electrobeauce.com",
    "statusKey": "active",
    "statusDetail": "Active (current listings)",
    "statusNote": "Public directory and construction-license listings show current contact information.",
    "sourceUrl": "https://www.construction411.com/electriciens/st-georges/electro-beauce/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "1",
    "supplierName": "ELECTRO-MIKE",
    "address": "1375 rue Frank-Carrel, Québec, QC G1N 2E7, Canada",
    "phone": "418-681-4138",
    "email": "",
    "website": "http://www.electromike.com",
    "statusKey": "inactive",
    "statusDetail": "Likely inactive — verify",
    "statusNote": "Public listings persist, but a reported 2024 store closure conflicts with them; do not rely on this contact without calling.",
    "sourceUrl": "https://www.mapquest.com/ca/quebec/electro-mike-inc-456092351",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "406",
    "supplierName": "ELECTROPUCE ENR.",
    "address": "539 Route 108 RR 2, Saint-Romain, QC G0Y 1L0, Canada",
    "phone": "418-486-7447",
    "email": "",
    "website": "",
    "statusKey": "active",
    "statusDetail": "Active listing — verify",
    "statusNote": "Current directory listings show the business and phone; no official website was identified.",
    "sourceUrl": "https://www.pagesjaunes.ca/search/si/1/Boutiques%2Binformatiques/Milan%2BQC",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "354",
    "supplierName": "EQUIPEMENTS DE COUTURE SAWAN",
    "address": "",
    "phone": "",
    "email": "",
    "website": "",
    "statusKey": "verify",
    "statusDetail": "No reliable current match",
    "statusNote": "No current public contact record confidently matched to this name.",
    "sourceUrl": "",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "382",
    "supplierName": "EQUIPEMENTS HYDRAULIQUES M.R.G.",
    "address": "440 rue Bourque, Repentigny, QC J5Z 5A2, Canada",
    "phone": "514-328-9360",
    "email": "",
    "website": "https://equipementsmrg.ca",
    "statusKey": "active",
    "statusDetail": "Active (official website)",
    "statusNote": "Current MRG contact page and operating history are published online.",
    "sourceUrl": "https://equipementsmrg.ca/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "23",
    "supplierName": "EXCEL EQUIPEMENT DE COUTURE INC.",
    "address": "1990 boul. Le Corbusier, Laval, QC H7S 2R1, Canada",
    "phone": "450-687-5573",
    "email": "",
    "website": "https://excellemachineacoudre.com",
    "statusKey": "active",
    "statusDetail": "Active (official website)",
    "statusNote": "Confirmed as Excelle Machine à Coudre; the official site lists its Laval store, contact information, and current opening hours.",
    "sourceUrl": "https://excellemachineacoudre.com/pages/contact",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "226",
    "supplierName": "FESTO",
    "address": "5300 Explorer Drive, Mississauga, ON L4W 5G4, Canada",
    "phone": "1-877-463-3786",
    "email": "",
    "website": "https://www.festo.com/ca",
    "statusKey": "active",
    "statusDetail": "Active (official website)",
    "statusNote": "Canadian headquarters and customer service are confirmed by Festo.",
    "sourceUrl": "https://www.festo.com/ca/en/e/contact/sales-support-id_3770045/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "417",
    "supplierName": "GAGNON EQUIPEMENT",
    "address": "101 boulevard Est (Route 138), Maskinongé, QC J0K 1N0, Canada",
    "phone": "819-227-2245",
    "email": "",
    "website": "https://www.equipementsgagnon.ca",
    "statusKey": "verify",
    "statusDetail": "Likely active — name match",
    "statusNote": "Matched to Équipements G. Gagnon Inc.; confirm it is the inventory vendor.",
    "sourceUrl": "https://www.equipementsgagnon.ca/nous-contacter",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "40",
    "supplierName": "GENERAL BEARING INC.",
    "address": "",
    "phone": "",
    "email": "",
    "website": "",
    "statusKey": "verify",
    "statusDetail": "No reliable current match",
    "statusNote": "No safe current Canadian company match found from the name alone.",
    "sourceUrl": "",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "290",
    "supplierName": "GEOFFREY E. MACPHERSON INC.",
    "address": "",
    "phone": "",
    "email": "",
    "website": "",
    "statusKey": "verify",
    "statusDetail": "No reliable current match",
    "statusNote": "No safe current company match found from the inventory name alone.",
    "sourceUrl": "",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "14",
    "supplierName": "INDUSTRIES CURTIS",
    "address": "2400 S. 43rd Street, Milwaukee, WI 53219, USA",
    "phone": "800-657-0853",
    "email": "",
    "website": "https://www.curtisind.com",
    "statusKey": "active",
    "statusDetail": "Active — assumed Curtis Industries USA",
    "statusNote": "Exact historical supplier entity needs confirmation; the manufacturer is currently active.",
    "sourceUrl": "https://www.curtisind.com/about-us/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "284",
    "supplierName": "JACOBS THOMPSON",
    "address": "89 Kenhar Drive, Toronto, ON M9L 2R3, Canada",
    "phone": "416-749-0600",
    "email": "",
    "website": "https://www.foamparts.com",
    "statusKey": "active",
    "statusDetail": "Active (current operating business)",
    "statusNote": "The company operates as Jacobs & Thompson / FoamParts; historic legal entity records note a successor relationship.",
    "sourceUrl": "https://www.foamparts.com/2020/04/jacobs-thompson-inc-to-supply-face-shields-to-federal-government/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "393",
    "supplierName": "JACQUES LAMBERT",
    "address": "",
    "phone": "",
    "email": "",
    "website": "",
    "statusKey": "verify",
    "statusDetail": "Individual / no verified company match",
    "statusNote": "Inventory entry appears to be a person. No business contact is supplied to avoid attributing an unrelated public profile.",
    "sourceUrl": "",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "44",
    "supplierName": "LAROCQUE ELECTRIQUE ENR",
    "address": "250 rue Faillon Ouest, Montréal, QC H2R 2V7, Canada",
    "phone": "514-277-5577",
    "email": "",
    "website": "",
    "statusKey": "verify",
    "statusDetail": "Unverified — legacy directory listing",
    "statusNote": "No official current website or registry confirmation found.",
    "sourceUrl": "https://www.anugo.ca/en/city/montreal/electricien",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "203",
    "supplierName": "J.H. DROLET",
    "address": "2665 rue Terra-Jet, Saint-Cyrille-de-Wendover, QC J1Z 1B3, Canada",
    "phone": "819-474-2149",
    "email": "",
    "website": "https://drolet-equipementcnc.com",
    "statusKey": "active",
    "statusDetail": "Active (official website)",
    "statusNote": "Confirmed as Drolet Équipement CNC (J.H. Drolet); the official website lists the phone number and describes ongoing CNC-equipment distribution and services.",
    "sourceUrl": "https://drolet-equipementcnc.com/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "320",
    "supplierName": "LES FABRICATIONS PIERRE FLUET INC.",
    "address": "409 route 204, Saint-Ludger, QC, Canada, Quebec",
    "phone": "819-548-5189",
    "email": "",
    "website": "https://www.facebook.com/p/Les-Fabrications-Pierre-Fluet-inc-100063479649849/",
    "statusKey": "active",
    "statusDetail": "Active (official website)",
    "statusNote": "No current public contact record confidently matched to this name.",
    "sourceUrl": "https://www.facebook.com/p/Les-Fabrications-Pierre-Fluet-inc-100063479649849/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "143",
    "supplierName": "MACHINE A COUDRE DELISLE",
    "address": "9395 boul. Saint-Laurent, Montréal, QC H2N 1P6, Canada",
    "phone": "514-381-6237",
    "email": "",
    "website": "https://www.delislesewing.com",
    "statusKey": "active",
    "statusDetail": "Active (successor business)",
    "statusNote": "Machine à coudre Delisle became Équipement Delisle Inc.; current website is active.",
    "sourceUrl": "https://www.delislesewing.com/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "150",
    "supplierName": "MEUBLES ROUSSEAU",
    "address": "164 rue Principale, Lambton, QC G0M 1H0, Canada",
    "phone": "418-486-7782",
    "email": "",
    "website": "https://www.meublesrousseau.com",
    "statusKey": "active",
    "statusDetail": "Active (official / current listings)",
    "statusNote": "Current business website and a 2026 Quebec permit listing support active status.",
    "sourceUrl": "https://www.meublesrousseau.com/fr/pg-terms_fr",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "340",
    "supplierName": "MOTOPARTS",
    "address": "1124 rue St-Calixte, Plessisville, QC G6L 1N8, Canada",
    "phone": "819-362-7345",
    "email": "",
    "website": "https://equipex.ca",
    "statusKey": "active",
    "statusDetail": "Active (successor business)",
    "statusNote": "Motoparts rebranded with its related divisions as Equipex in 2024.",
    "sourceUrl": "https://equipex.ca/en/a-propos/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "409",
    "supplierName": "PFAFF CANADA INC.",
    "address": "4630 Dufferin Street, Downsview, ON M3H 5S4, Canada",
    "phone": "",
    "email": "",
    "website": "",
    "statusKey": "inactive",
    "statusDetail": "Inactive — discontinued",
    "statusNote": "The exact legal entity was discontinued on 1996-12-27. This row does not represent the current PFAFF brand or distributors.",
    "sourceUrl": "https://www.can1business.com/company/Inactive-Discontinued/Pfaff-Canada-Inc",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "38",
    "supplierName": "PHILIPPE MERCIER",
    "address": "3945 rue Laval, Lac-Mégantic, QC G6B 1A7, Canada",
    "phone": "819-583-2622",
    "email": "",
    "website": "https://pmercier.com",
    "statusKey": "active",
    "statusDetail": "Active (official website / licence)",
    "statusNote": "Philippe Mercier (1994) inc. is listed with an active Québec contractor licence.",
    "sourceUrl": "https://pmercier.com/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "22",
    "supplierName": "PIECES D.R. INC.",
    "address": "2509 rue Sherbrooke, Magog, QC J1X 4R7, Canada",
    "phone": "819-843-0550",
    "email": "",
    "website": "",
    "statusKey": "verify",
    "statusDetail": "Likely active — assumed Pièces d'Autos D.R.",
    "statusNote": "Matched to a current automotive-parts business; confirm this is the inventory supplier before using.",
    "sourceUrl": "https://performanceplusbrakes.ca/locations/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "43",
    "supplierName": "PNEUTECH",
    "address": "1475 32e Avenue, Lachine, QC H8T 3J1, Canada",
    "phone": "514-635-7000",
    "email": "",
    "website": "https://www.pneutech-rousseau.com",
    "statusKey": "active",
    "statusDetail": "Active (successor / official website)",
    "statusNote": "Pneutech is currently presented as Pneutech-Rousseau.",
    "sourceUrl": "https://www.pneutech-rousseau.com/fr/contact/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "408",
    "supplierName": "PRO-HYDRAULIQUE",
    "address": "2585 avenue Dalton, Québec, QC G1P 3S7, Canada",
    "phone": "418-659-3924",
    "email": "",
    "website": "https://www.applied.com",
    "statusKey": "active",
    "statusDetail": "Active (current branch listing)",
    "statusNote": "Current Applied Industrial Technologies listing identifies Pro-Hydraulique at this location.",
    "sourceUrl": "https://www.applied.com/store/PRO%20HYDRAULIQUE?lat=45.5018869&long=-73.5673919&q=montreal+quebec",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "24",
    "supplierName": "RAU CANADA",
    "address": "",
    "phone": "",
    "email": "",
    "website": "",
    "statusKey": "verify",
    "statusDetail": "No reliable current match",
    "statusNote": "No safe current Canadian company match found from the name alone.",
    "sourceUrl": "",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "390",
    "supplierName": "RUBANS HUBSCHER LTEE. (HUBSCHERCORP)",
    "address": "2325, 52e Avenue, Lachine, QC H8T 3C3, Canada",
    "phone": "514-636-6610",
    "email": "",
    "website": "https://hubschercorp.com",
    "statusKey": "active",
    "statusDetail": "Active (official website)",
    "statusNote": "Confirmed as Hubschercorp / Hubscher Ribbon Corp. The official site describes an active Montréal operation supplying decorative ribbons, bows, apparel labeling, and premium packaging; the Montréal address and phone are supported by a current business directory.",
    "sourceUrl": "https://hubschercorp.com/pages/about-us",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "25",
    "supplierName": "RUBENSTEIN BROS CO. INC. (REECE)",
    "address": "697 rue Gougeon, Montréal, QC H4T 2B4, Canada",
    "phone": "800-361-0100",
    "email": "",
    "website": "https://rbdigital.ca",
    "statusKey": "active",
    "statusDetail": "Active (official website)",
    "statusNote": "Confirmed as Rubenstein RB Digital Inc. (RB Digital); its official site lists the Montréal location and indicates national operations.",
    "sourceUrl": "https://rbdigital.ca/pages/contact",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "26",
    "supplierName": "RUBENSTEIN BROS. CO. INC.",
    "address": "865 rue Hodge, Saint-Laurent, QC H4N 2B1, Canada",
    "phone": "514-747-0600",
    "email": "",
    "website": "",
    "statusKey": "active",
    "statusDetail": "Active (current directory listing)",
    "statusNote": "Current directory listing identifies the firm at the Montréal address.",
    "sourceUrl": "https://www.pagesjaunes.ca/search/si/1/Rubenstein-Bros-Co-Inc/Montreal%2BQC",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "70",
    "supplierName": "SHER-LENN",
    "address": "950 rue Wellington Sud, Sherbrooke, QC J1H 5E7, Canada",
    "phone": "819-569-9494",
    "email": "",
    "website": "https://silencieuxsherlenn.com",
    "statusKey": "active",
    "statusDetail": "Active (official website)",
    "statusNote": "Operating as Silencieux Sher-Lenn.",
    "sourceUrl": "https://silencieuxsherlenn.com/a-propos/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "145",
    "supplierName": "STRAPEX",
    "address": "Silbernstrasse 14, 8953 Dietikon, Switzerland",
    "phone": "+41 44 745 50 50",
    "email": "",
    "website": "https://www.strapex.com",
    "statusKey": "active",
    "statusDetail": "Active (global brand)",
    "statusNote": "The global company is active. A current Canadian legal entity/contact was not independently verified; the listed address is global HQ.",
    "sourceUrl": "https://www.strapex.com/contact.html",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "134",
    "supplierName": "TECHNIC INC.",
    "address": "47 Molter Street, Cranston, RI 02910, USA",
    "phone": "401-781-6100",
    "email": "",
    "website": "https://www.technic.com",
    "statusKey": "active",
    "statusDetail": "Active — assumed Technic Inc. USA",
    "statusNote": "Exact historical Canadian supplier entity needs confirmation; Technic's global manufacturer is active.",
    "sourceUrl": "https://www.technic.com/sites/default/files/resources/Technic%20Semiconductor%20Products.pdf",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "29",
    "supplierName": "UNION SPECIAL CANADA LTD.",
    "address": "5205 boul. Métropolitain Est, Saint-Léonard, QC H1R 1Z7, Canada",
    "phone": "514-329-4813",
    "email": "",
    "website": "https://www.unionspecial.com",
    "statusKey": "verify",
    "statusDetail": "Legacy Canadian entity — verify",
    "statusNote": "The brand is active, but no current official confirmation for the Canadian legal entity was found. Address and phone are legacy directory data.",
    "sourceUrl": "https://www.anugo.ca/en/business/180777-union-special-canada-ltd-sewing-machine-stores-saint-leonard",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "445",
    "supplierName": "USIFAB R.L.INC.",
    "address": "Route 271 Nord, Saint-Éphrem-de-Beauce, QC, Canada",
    "phone": "",
    "email": "",
    "website": "",
    "statusKey": "verify",
    "statusDetail": "Unverified — limited current evidence",
    "statusNote": "Recent professional-profile evidence references Usifab R.L. in Saint-Éphrem, but no public direct contact was found.",
    "sourceUrl": "https://ca.linkedin.com/in/v%C3%A9ronique-boulet-38028720",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "103",
    "supplierName": "USINAGE RAY JEAN",
    "address": "2345, 95e Rue, Saint-Georges, QC G5Y 8J2, Canada",
    "phone": "418-228-0337",
    "email": "",
    "website": "https://www.usinagerayjean.com",
    "statusKey": "active",
    "statusDetail": "Active (official website)",
    "statusNote": "Operating as Atelier d'Usinage Ray-Jean Inc.",
    "sourceUrl": "https://www.usinagerayjean.com/",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "347",
    "supplierName": "USINAGES SIM-COT",
    "address": "2516-263 Route 263, RR 3, Disraeli, QC G0N 1E0",
    "phone": "418-449-2222",
    "email": "",
    "website": "",
    "statusKey": "verify",
    "statusDetail": "Unverified — limited current evidence",
    "statusNote": "",
    "sourceUrl": "https://apps.gestionweblex.ca/doc-list/handlers/document.ashx?documentid=f47385fd-d56b-4d6b-ae43-d21a771722d2",
    "verifiedDate": "2026-07-29"
  },
  {
    "supplierCode": "210",
    "supplierName": "WAINBEE LTEE.",
    "address": "215 boul. Brunswick, Pointe-Claire, QC H9R 4R7, Canada",
    "phone": "514-697-8810",
    "email": "",
    "website": "https://www.wainbee.com",
    "statusKey": "active",
    "statusDetail": "Active (official website)",
    "statusNote": "Current Montréal location is listed by Wainbee.",
    "sourceUrl": "https://www.wainbee.com/en/locations",
    "verifiedDate": "2026-07-29"
  }
];

// The old inventory used these shortened supplier labels. They intentionally
// inherit the researched contact record instead of creating a guessed company.
export const supplierContactAliases = [
  { legacySupplierName: "A.M.F.", researchedSupplierName: "AMC REECE (A.M.F.)" },
  { legacySupplierName: "LEA AGENCES J.H. DROLET", researchedSupplierName: "J.H. DROLET" },
  { legacySupplierName: "RUBANS HUBSCHER LTEE.", researchedSupplierName: "RUBANS HUBSCHER LTEE. (HUBSCHERCORP)" },
];
