#!/usr/bin/env ruby
# frozen_string_literal: true

# Converts the reviewed machine-association audit into a versioned application
# seed. The recovered inventory remains the validation source; this script
# refuses to generate output if a proposed row no longer joins exactly or if
# its audited previous label differs from the recovered value.

require "csv"
require "json"

source_path = ARGV.fetch(0) do
  abort "Usage: ruby scripts/import-machine-association-audit.rb /path/to/proposed_machine_association_changes.csv"
end

def normalized_machine(value)
  value.to_s.upcase.gsub(/[^A-Z0-9]/, "")
end

def expect(condition, message)
  abort "Import validation failed: #{message}" unless condition
end

inventory_source = File.read("app/lib/inventory-seed.ts")
inventory_json = inventory_source[/export const inventorySeed: InventorySeedRow\[\] = (\[.*\]);\s*\z/m, 1]
expect(inventory_json, "could not read the generated inventory seed")
inventory_rows = JSON.parse(inventory_json)
inventory_by_key = inventory_rows.to_h do |row|
  [[row.fetch("legacyReference"), row.fetch("supplierCategoryCode")], row]
end

source_rows = CSV.read(source_path, headers: true, encoding: "bom|utf-8").map(&:to_h)
expect(source_rows.length == 92, "expected 92 proposed changes, found #{source_rows.length}")

keys = source_rows.map { |row| [row.fetch("legacy_reference"), row.fetch("supplier_category_code")] }
expect(keys.uniq.length == source_rows.length, "proposed-change join keys are not unique")

seed_rows = source_rows.map do |row|
  key = [row.fetch("legacy_reference"), row.fetch("supplier_category_code")]
  inventory_row = inventory_by_key[key]
  expect(inventory_row, "inventory record #{key.join("/")} is missing")
  expect(
    normalized_machine(inventory_row.fetch("machineModel")) == normalized_machine(row.fetch("current_machine_association")),
    "audited current machine does not match recovered inventory for #{key.join("/")}"
  )
  expect(!row.fetch("proposed_machine_association").strip.empty?, "blank proposed association for #{key.join("/")}")

  {
    legacyReference: row.fetch("legacy_reference"),
    supplierCategoryCode: row.fetch("supplier_category_code"),
    currentMachineAssociation: row.fetch("current_machine_association"),
    proposedMachineAssociation: row.fetch("proposed_machine_association"),
    associationType: row.fetch("association_type"),
    auditClassification: row.fetch("audit_classification"),
    confidence: row.fetch("confidence"),
    evidenceUrls: row.fetch("evidence_urls"),
    evidenceSourceType: row.fetch("evidence_source_type"),
    rationale: row.fetch("rationale"),
    nextPhysicalVerificationStep: row.fetch("next_physical_verification_step"),
    proposedChangeBasis: row.fetch("proposed_change_basis")
  }
end

output = <<~TS
  // Generated from the 2026-07-29 machine-association audit.
  // The guarded runtime import preserves the previous label as a searchable alias.
  // Do not edit this file by hand.

  export const machineAssociationAuditSnapshot = {
    importKey: "machine-association-audit-2026-07-29-v1",
    sourceName: "NF Denim supplier-part-number machine-association audit",
    reviewer: "Gigi",
    reviewedAt: "2026-07-29",
    approvalNote: "User approved applying the proposed associations while preserving previous labels as searchable aliases.",
  } as const;

  export type MachineAssociationAuditSeedRow = {
    legacyReference: string;
    supplierCategoryCode: string;
    currentMachineAssociation: string;
    proposedMachineAssociation: string;
    associationType: string;
    auditClassification: string;
    confidence: string;
    evidenceUrls: string;
    evidenceSourceType: string;
    rationale: string;
    nextPhysicalVerificationStep: string;
    proposedChangeBasis: string;
  };

  export const machineAssociationAuditSeed: MachineAssociationAuditSeedRow[] = #{JSON.pretty_generate(seed_rows)};
TS

File.write("app/lib/machine-association-audit-seed.ts", output)
puts "Imported #{seed_rows.length} reviewed machine associations with exact recovered-inventory joins."
